apiVersion: apps/v1
kind: Deployment
metadata:
  name: edu1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: edu1
  template:
    metadata:
      labels:
        app: edu1
    spec:
      containers:
      - name: edu1
        image: icishub.azurecr.io/shclub/edu1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
